class EnvConfig:
    SAFE_TEMP_MIN = 2.0
    SAFE_TEMP_MAX = 8.0
    CRITICAL_TEMP_HIGH = 10.0
    IDEAL_TEMP = 5.0
    MAX_BATTERY = 100.0
    AMBIENT_TEMP_BASE = 25.0
    THERMAL_CONDUCTIVITY_K = 0.02 
    PASSIVE_HEAT_Q = 0.1 
    COOLING_POWER = [0.0, -0.5, -1.0, -2.0]
    BATTERY_DRAIN_COOLING = [0.1, 0.5, 1.0, 2.5]
    BATTERY_DRAIN_BASE = 0.1
    BATTERY_DRAIN_SYNC = 1.0
    TEMP_DRIFT_WARM = 0.5 
    DEFAULT_EXPIRY_STEPS = 50
    EXPIRY_ACCEL_FACTOR = 2.0 
    WEAR_PENALTY_WEIGHT = 0.5        
    EXPONENTIAL_MARGIN_WEIGHT = 1.0  
